[package]
name = "tobytcp"
version = "0.11.0"
authors = ["Ryan Gorup"]
categories = ["tcp"]
keywords = ["tcp"]
repository = "https://github.com/gorup/tobytcp"
description = "A little library for sending messages over a raw tcp stream"
license-file = "LICENSE"
readme="README.md"

[dependencies]
log = "0.4"
uuid = { version = "0.6", features = ["v4"] }
